name: Update GitHub Stats Gist

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'
  push:
    branches:
      - master

jobs:
  github-stats-box:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16
          
      - name: Update GitHub Stats Box
        run: npx github-stats-box@1
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 07206a124b17d24ffea7dcc85caa6113
          ALL_COMMITS: true
          K_FORMAT: false

  productive-box:
    runs-on: ubuntu-latest
    steps:
      - name: Update gist
        uses: maxam2017/productive-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: df5881bb693bdf5ff508a2de8367c38b
          TIMEZONE: Asia/Seoul
